title: "Technical Documentation — Work Sample"
description: "This repository contains sample technical documentation created to demonstrate my technical writing capabilities."
theme: jekyll-theme-minimal
markdown: kramdown

include:
  - "Installation-Guide.md"
  - "Release_Notes.md"
  - "API Docs.md"
  - "User guide.md"
  - "API-Docs-using-Postman.md"
  - "Video-creation-sample.md"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
