title: Technical Documentation – Work Sample
description: This repository contains sample technical documentation created to demonstrate my technical writing capabilities.
theme: jekyll-theme-minimal

markdown: kramdown

include:
    - [Installation Guide](Installation-Guide.md)
    - [Release Notes](Release_Notes.md)
    - [API Documentation Sample](API Docs.md)
    - [User Guide Sample](User guide.md)
    - [API Documentation using Postman Tool](API-Docs-using-Postman.md)
    - [Sample Demo Video with Voiceover](Video-creation-sample.md)

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
