title: Technical Documentation – Work Sample
description: This repository contains sample technical documentation created to demonstrate my technical writing capabilities.
theme: jekyll-theme-minimal

markdown: kramdown

include:
    - release-notes.md
    - installation-guide.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
